version: "3.7"
services:
  mariadbBackend:
    container_name: insyMariaDB
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mymaria
    ports:
      - "6789:3306"
